version: '3'

services:

  redis-master:
    container_name: redis-master
    image: redis:5.0.6-alpine
    volumes:
      - "./data/redis-master:/data"
    ports:
      - "5001:6379"
  redis-slave:
    container_name: redis-slave
    image: redis:5.0.6-alpine
    command: redis-server --slaveof redis-master 6379
    volumes:
      - "./data/redis-slave:/data"
    links:
      - redis-master
    ports:
      - "5002:6379"
  redis-sentinel-1:
    container_name: redis-sentinel-1
    build: redis-sentinel
    links:
      - redis-master

  redis-sentinel-2:
    container_name: redis-sentinel-2
    build: redis-sentinel
    links:
      - redis-master

  redis-sentinel-3:
    container_name: redis-sentinel-3
    build: redis-sentinel
    links:
      - redis-master
